const event_Types = {
    SET_DROPDOWN_BEGIN: 'SET_DROPDOWN_BEGIN',
    SET_DROPDOWN_VALUES: 'SET_DROPDOWN_VALUES',
    SET_DROPDOWN_VALUES_ERROR: 'SET_DROPDOWN_VALUES_ERROR'
}
export default event_Types;